/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.project4;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Date;
import javax.swing.JOptionPane;



/**
 *
 * @author comzone
 */
public class Form1 extends javax.swing.JFrame {
    
    

    /**
     * Creates new form Form1
     */
    public Form1(String[] listprovince) {
        initComponents();
          for(String s:listprovince){ // foreach loop in java
            //s->1
            //s->2
            //s->3
            //s->4
            Box1.addItem(s);

           
       
    }

    }

    Form1() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        p_t = new javax.swing.JLabel();
        pp1 = new javax.swing.JRadioButton();
        st1 = new javax.swing.JRadioButton();
        lc = new javax.swing.JLabel();
        txtText = new javax.swing.JTextField();
        lc2 = new javax.swing.JLabel();
        Box1 = new javax.swing.JComboBox<>();
        ppnum = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pt_show = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jtext = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("บริษัท  เซ็นจูทัวร์  จำกัด");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 23, 183, -1));

        jLabel2.setFont(new java.awt.Font("Angsana New", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("บริการ รถตู้V.I.P ออนไลน์ 24ชม.");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 57, 173, -1));

        p_t.setFont(new java.awt.Font("Angsana New", 0, 18)); // NOI18N
        p_t.setText("ประเภทผู้โดยสาร");
        getContentPane().add(p_t, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 135, -1, -1));

        pp1.setFont(new java.awt.Font("Angsana New", 0, 18)); // NOI18N
        pp1.setText("บุคคลทั่วไป");
        getContentPane().add(pp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 131, -1, -1));

        st1.setFont(new java.awt.Font("Angsana New", 0, 18)); // NOI18N
        st1.setText("นักเรียน,นักศึกษา,คณะครูอาจาร์ย");
        getContentPane().add(st1, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 131, -1, -1));

        lc.setFont(new java.awt.Font("Angsana New", 0, 18)); // NOI18N
        lc.setText("จุดนัดรับ");
        getContentPane().add(lc, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 190, -1, -1));

        txtText.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 15)); // NOI18N
        getContentPane().add(txtText, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 190, 269, -1));

        lc2.setFont(new java.awt.Font("Angsana New", 0, 18)); // NOI18N
        lc2.setText("ปลายทาง(จังหวัด)");
        getContentPane().add(lc2, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 236, -1, -1));

        Box1.setFont(new java.awt.Font("Angsana New", 0, 18)); // NOI18N
        Box1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box1ActionPerformed(evt);
            }
        });
        getContentPane().add(Box1, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 232, 269, -1));

        ppnum.setFont(new java.awt.Font("Angsana New", 0, 18)); // NOI18N
        ppnum.setText("จำนวนผู้โดยสาร");
        getContentPane().add(ppnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 291, -1, -1));

        pt_show.setColumns(20);
        pt_show.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        pt_show.setRows(5);
        jScrollPane1.setViewportView(pt_show);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 378, 379, 148));

        jButton1.setFont(new java.awt.Font("Angsana New", 0, 18)); // NOI18N
        jButton1.setText("คำนวน");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 328, -1, -1));

        jButton2.setFont(new java.awt.Font("Angsana New", 0, 18)); // NOI18N
        jButton2.setText("เคลียร์");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 328, -1, -1));

        jButton3.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        jButton3.setText("ใบเสร็จ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 329, -1, 31));

        jtext.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        getContentPane().add(jtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 110, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:  
        String name = "";
        String number ="";       
        int money = 0;
        double money2 = 0;
        double markedprice=100;
        Date date = new Date();
        

        
        if(pp1.isSelected()==true){
        money = money+60 ;
        name += "บุคคลทั่วไป  :     60 บาท \n";
        }
        if(st1.isSelected()==true){
        money = money+40;
        name += "นักเรียน,นักศึกษา,คณะครูอาจาร์ย   :        40 บาท  \n";
        }
        
        money2 = Double.parseDouble(jtext.getText());
        money = (int) (money*money2);
        
         
                   

        pt_show.setText(name + "\n" +"จำนวน : "+jtext.getText()+" คน "+"\n"+"จุดขึ้นรถ : "+txtText.getText()+"\n"+"จุดหมายปลายทาง(จังหวัด) : " 
                +Box1.getSelectedItem()+"\n"+ "รวม : " + money+ " บาท "+"\n"+"ลงเวลา : " 
                + date.toString()+"\n\n"+"บึนทึกไปที่ :"+"C:\\Users\\comzone\\Desktop\\ใบเสร็จ.txt" );
         String selectedProvince = String.valueOf(Box1.getSelectedItem());
         
         
         
       
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Box1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box1ActionPerformed
        // TODO add your handling code here:       
    }//GEN-LAST:event_Box1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        pt_show.setText("  ");
        txtText.setText("   ");
        Box1.setSelectedIndex(0);
        pp1.setSelected(false);
        st1.setSelected(false);
        jtext.setText(" ");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         String path = "C:\\Users\\comzone\\Desktop\\ใบเสร็จ.txt";
        File file = new File(path);
        FileWriter writer;
        try {
           writer = new FileWriter(file,true);
           writer.write(pt_show.getText());
           writer.close();
           
           System.out.println("Write success!");           
        }catch (IOException e) {
          e.printStackTrace();        
        }
        
  
      
        JOptionPane.showMessageDialog(null,pt_show );
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Box1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jtext;
    private javax.swing.JLabel lc;
    private javax.swing.JLabel lc2;
    private javax.swing.JLabel p_t;
    private javax.swing.JRadioButton pp1;
    private javax.swing.JLabel ppnum;
    private javax.swing.JTextArea pt_show;
    private javax.swing.JRadioButton st1;
    private javax.swing.JTextField txtText;
    // End of variables declaration//GEN-END:variables

    private void showDataBox1() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void clearData() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
